# These are supported funding model platforms

github: [BanchanArt] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
open_collective: banchan-art # Replace with a single Open Collective username

