name: Deploy to Production
on:
  release:
    types: [released]

env:
  BANCHAN_DEPLOY_ENV: prod
  BANCHAN_HOST: banchan.art

jobs:
  deploy:
    name: Deploy Banchan to Production Server
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://banchan.art
    strategy:
      matrix:
        elixir: [1.14.5]
        otp: [25]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Setup BEAM
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}

      - run: mix deploy.prod --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_DEV_DEPLOY_API_TOKEN }}

